# FROM crpi-vkjftqt0qsdk2jmc.cn-shanghai.personal.cr.aliyuncs.com/pysunday/sdenv_base:arm64
# FROM crpi-vkjftqt0qsdk2jmc.cn-shanghai.personal.cr.aliyuncs.com/pysunday/sdenv_base:x86_64

ENV NODE_PATH=/usr/local/lib/node_modules
RUN n 20 && npm install -g npm@latest node-gyp@latest sdenv@latest
COPY example example

ENTRYPOINT ["/usr/local/bin/node"]
